### ISSUE TITLE
CMake Error at CMakeLists.txt:17: Cannot find source file archive/x.cpp

### ISSUE THREAD

**Issue by FilipDominec** [MrYsLab/Telemetrix4RpiPico#7]
Trying to get the project compiled along the standard procedure [1] that works e.g. for blink.c from pico-examples, I get an CMake error instead:

```
PICO_SDK_PATH is /home/dominecf/bin/pico-sdk
PICO platform is rp2040.
PICO target board is pico.
Using board configuration from /home/dominecf/bin/pico-sdk/src/boards/include/boards/pico.h
TinyUSB available at /home/dominecf/bin/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; adding USB support.
-- Configuring done
CMake Error at CMakeLists.txt:17 (add_executable):
  Cannot find source file:

    archive/x.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:17 (add_executable):
  No SOURCES given to target: pio_Telemetrix4RpiPico


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I can see there may be a file missing in the CMakelists.txt on line 17:

    add_executable(pio_Telemetrix4RpiPico archive/x.cpp)

What am I doing wrong? Obviously line #17 defines a build target, so commenting it out would break the rest of the process.

[1]: https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf, described on pp. 6−7.

**Comment by FilipDominec** [comment]
Commenting the apparently obsoleted line 17 in CMakelists.txt out, I get another error:

```
cmake_minimum_required(VERSION 3.12)
set(CMAKE_CXX_STANDARD 14)
include(pico_sdk_import.cmake)
project(Telemetrix4RpiPico)
pico_sdk_init()
add_executable(Telemetrix4RpiPico
        Telemetrix4RpiPico.c
)

pico_generate_pio_header(Telemetrix4RpiPico ${CMAKE_CURRENT_LIST_DIR}/Telemetrix4RpiPico.pio archive/hc_sr04.pio)
pico_enable_stdio_usb(Telemetrix4RpiPico 1)
pico_add_extra_outputs(Telemetrix4RpiPico)
target_link_libraries(Telemetrix4RpiPico pico_stdlib hardware_pwm
        pico_unique_id hardware_watchdog hardware_adc hardware_i2c
        hardware_pio hardware_clocks hardware_spi)

### add_executable(pio_Telemetrix4RpiPico archive/x.cpp)
# generate the header file into the source tree as it is included in the RP2040 datasheet
pico_generate_pio_header(pio_Telemetrix4RpiPico ${CMAKE_CURRENT_LIST_DIR}/Telemetrix4RpiPico.pio archive/hc_sr04.pio
        OUTPUT_DIR ${CMAKE_CURRENT_LIST_DIR}/generated)

target_sources(pio_Telemetrix4RpiPico PRIVATE Telemetrix4RpiPico.c)
pico_add_extra_outputs(pio_Telemetrix4RpiPico)

add_custom_target(pio_Telemetrix4RpiPico_datasheet DEPENDS ${CMAKE_CURRENT_LIST_DIR}/generated/Telemetrix4RpiPico.py)
add_custom_command(OUTPUT ${CMAKE_CURRENT_LIST_DIR}/generated/Telemetrix4RpiPico.py
        DEPENDS Telemetrix4RpiPico.pio archive/hc_sr04.pio
        COMMAND Pioasm -o python Telemetrix4RpiPico.pio archive/hc_sr04.pio ./generated/Telemetrix4RpiPico
        )
add_dependencies(pio_Telemetrix4RpiPico pio_Telemetrix4RpiPico_datasheet)
```

**Comment by MrYsLab** [comment]
Sorry about that. I updated the CMakeLists.txt file and that should solve that problem. The "archive" files were probably erroneously added when I refactored using CLion.

Please let me know if things now compile for you.

**Comment by FilipDominec** [comment]
Unfortunately, I am still unable to compile it. Using the standard procedure from official guide (getting-started-with-pico.pdf, pp. 8-9) I am able to compile the pico-examples repository on Ubuntu 20.04; however your project seems to use different settings. 

Could you please give me a hint, e.g. some user-defined constants in CLions IDE? I have been trying for hours, but I cannot trace the difference. 

```
dominecf@filip-hp280g1mt:~/p/Telemetrix4RpiPico $ ls $PICO_SDK_PATH
cmake  CMakeLists.txt  docs  external  lib  LICENSE.TXT  pico_sdk_init.cmake  pico_sdk_version.cmake  README.md  src  test  tools


dominecf@filip-hp280g1mt:~/p/Telemetrix4RpiPico $ cmake .
PICO_SDK_PATH is /home/dominecf/bin/pico-sdk
PICO platform is rp2040.
PICO target board is pico.
Using board configuration from /home/dominecf/bin/pico-sdk/src/boards/include/boards/pico.h
TinyUSB available at /home/dominecf/bin/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; adding USB support.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dominecf/p/Telemetrix4RpiPico


dominecf@filip-hp280g1mt:~/p/Telemetrix4RpiPico $ make
[  1%] Performing build step for 'ELF2UF2Build'
[100%] Built target elf2uf2
[  2%] No install step for 'ELF2UF2Build'
[  3%] Completed 'ELF2UF2Build'
[  8%] Built target ELF2UF2Build
[  9%] Performing build step for 'PioasmBuild'
[100%] Built target pioasm
[ 10%] No install step for 'PioasmBuild'
[ 11%] Completed 'PioasmBuild'
[ 16%] Built target PioasmBuild
[ 17%] Generating generated/Telemetrix4RpiPico.py
[ 17%] Built target pio_Telemetrix4RpiPico_datasheet
[ 18%] Built target pio_Telemetrix4RpiPico_Telemetrix4RpiPico_pio_h
[ 19%] Building C object CMakeFiles/pio_Telemetrix4RpiPico.dir/Telemetrix4RpiPico.c.obj
In file included from /home/dominecf/p/Telemetrix4RpiPico/Telemetrix4RpiPico.c:34:
/home/dominecf/p/Telemetrix4RpiPico/include/Telemetrix4RpiPico.h:13:10: fatal error: pico/stdlib.h: No such file or directory
   13 | #include "pico/stdlib.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pio_Telemetrix4RpiPico.dir/build.make:63: CMakeFiles/pio_Telemetrix4RpiPico.dir/Telemetrix4RpiPico.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1573: CMakeFiles/pio_Telemetrix4RpiPico.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by FilipDominec** [comment]
I upgraded my ```cmake``` version to the latest available (3.21.2), but no obvious change. Full printout from a fresh attempt of compilation follows.

```
dominecf@filip-hp280g1mt:~/tm/Telemetrix4RpiPico $ /home/dominecf/.local/lib/python3.8/site-packages/cmake/data/bin/cmake . -DPICO_SDK_PATH=/home/dominecf/bin/pico-sdk && make
PICO_SDK_PATH is /home/dominecf/bin/pico-sdk
Defaulting PICO_PLATFORM to rp2040 since not specified.
Defaulting PICO platform compiler to pico_arm_gcc since not specified.
-- Defaulting build type to 'Release' since not specified.
PICO compiler is pico_arm_gcc
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
Defaulting PICO target board to pico since not specified.
Using board configuration from /home/dominecf/bin/pico-sdk/src/boards/include/boards/pico.h
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
TinyUSB available at /home/dominecf/bin/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; adding USB support.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dominecf/tm/Telemetrix4RpiPico
Scanning dependencies of target bs2_default
[  1%] Building ASM object pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/compile_time_choice.S.obj
[  2%] Linking ASM executable bs2_default.elf
[  2%] Built target bs2_default
[  3%] Generating bs2_default.bin
[  4%] Generating bs2_default_padded_checksummed.S
[  4%] Built target bs2_default_padded_checksummed_asm
[  5%] Creating directories for 'ELF2UF2Build'
[  6%] No download step for 'ELF2UF2Build'
[  7%] No update step for 'ELF2UF2Build'
[  8%] No patch step for 'ELF2UF2Build'
[  9%] Performing configure step for 'ELF2UF2Build'
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dominecf/tm/Telemetrix4RpiPico/elf2uf2
[ 10%] Performing build step for 'ELF2UF2Build'
[ 50%] Building CXX object CMakeFiles/elf2uf2.dir/main.cpp.o
[100%] Linking CXX executable elf2uf2
[100%] Built target elf2uf2
[ 11%] No install step for 'ELF2UF2Build'
[ 12%] Completed 'ELF2UF2Build'
[ 12%] Built target ELF2UF2Build
[ 13%] Creating directories for 'PioasmBuild'
[ 14%] No download step for 'PioasmBuild'
[ 15%] No update step for 'PioasmBuild'
[ 16%] No patch step for 'PioasmBuild'
[ 17%] Performing configure step for 'PioasmBuild'
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dominecf/tm/Telemetrix4RpiPico/pioasm
[ 18%] Performing build step for 'PioasmBuild'
[ 10%] Building CXX object CMakeFiles/pioasm.dir/main.cpp.o
[ 20%] Building CXX object CMakeFiles/pioasm.dir/pio_assembler.cpp.o
[ 30%] Building CXX object CMakeFiles/pioasm.dir/pio_disassembler.cpp.o
[ 40%] Building CXX object CMakeFiles/pioasm.dir/gen/lexer.cpp.o
[ 50%] Building CXX object CMakeFiles/pioasm.dir/gen/parser.cpp.o
[ 60%] Building CXX object CMakeFiles/pioasm.dir/c_sdk_output.cpp.o
[ 70%] Building CXX object CMakeFiles/pioasm.dir/python_output.cpp.o
[ 80%] Building CXX object CMakeFiles/pioasm.dir/hex_output.cpp.o
[ 90%] Building CXX object CMakeFiles/pioasm.dir/ada_output.cpp.o
[100%] Linking CXX executable pioasm
[100%] Built target pioasm
[ 19%] No install step for 'PioasmBuild'
[ 20%] Completed 'PioasmBuild'
[ 20%] Built target PioasmBuild
[ 21%] Generating Telemetrix4RpiPico.pio.h
[ 21%] Built target Telemetrix4RpiPico_Telemetrix4RpiPico_pio_h
Scanning dependencies of target Telemetrix4RpiPico
[ 22%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/Telemetrix4RpiPico.c.obj
[ 23%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
[ 24%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
[ 25%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
[ 26%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
[ 27%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
[ 28%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
[ 29%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
[ 30%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_time/time.c.obj
[ 31%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_time/timeout_helper.c.obj
[ 32%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
[ 33%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_sync/sem.c.obj
[ 34%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_sync/lock_core.c.obj
[ 35%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_sync/mutex.c.obj
[ 36%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_sync/critical_section.c.obj
[ 37%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_util/datetime.c.obj
[ 38%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_util/pheap.c.obj
[ 39%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/common/pico_util/queue.c.obj
[ 40%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
[ 41%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
[ 42%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
[ 43%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
[ 44%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
[ 45%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
[ 46%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
[ 47%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
[ 48%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
[ 50%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
[ 51%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
[ 52%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
[ 53%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
[ 54%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
[ 55%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
[ 56%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
[ 57%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
[ 58%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
[ 59%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
[ 60%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
[ 61%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
[ 62%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
[ 63%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
[ 64%] Building ASM object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
[ 65%] Building CXX object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
[ 66%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
[ 67%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
[ 68%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
[ 69%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_stdio_usb/reset_interface.c.obj
[ 70%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_stdio_usb/stdio_usb.c.obj
[ 71%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_stdio_usb/stdio_usb_descriptors.c.obj
[ 72%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040/dcd_rp2040.c.obj
[ 73%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040/rp2040_usb.c.obj
[ 74%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/device/usbd.c.obj
[ 75%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/device/usbd_control.c.obj
[ 76%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/audio/audio_device.c.obj
[ 77%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/cdc/cdc_device.c.obj
[ 78%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/dfu/dfu_device.c.obj
[ 79%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/dfu/dfu_rt_device.c.obj
[ 80%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/hid/hid_device.c.obj
[ 81%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/midi/midi_device.c.obj
[ 82%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/msc/msc_device.c.obj
[ 83%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/net/net_device.c.obj
[ 84%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/usbtmc/usbtmc_device.c.obj
[ 85%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/class/vendor/vendor_device.c.obj
[ 86%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/tusb.c.obj
[ 87%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/lib/tinyusb/src/common/tusb_fifo.c.obj
[ 88%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_fix/rp2040_usb_device_enumeration/rp2040_usb_device_enumeration.c.obj
[ 89%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/pico_unique_id/unique_id.c.obj
[ 90%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_flash/flash.c.obj
[ 91%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_adc/adc.c.obj
[ 92%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_i2c/i2c.c.obj
[ 93%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_pio/pio.c.obj
[ 94%] Building C object CMakeFiles/Telemetrix4RpiPico.dir/home/dominecf/bin/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj
[ 95%] Linking CXX executable Telemetrix4RpiPico.elf
[ 95%] Built target Telemetrix4RpiPico
[ 96%] Generating generated/Telemetrix4RpiPico.py
[ 96%] Built target pio_Telemetrix4RpiPico_datasheet
[ 97%] Generating generated/Telemetrix4RpiPico.pio.h
[ 97%] Built target pio_Telemetrix4RpiPico_Telemetrix4RpiPico_pio_h
[ 98%] Building C object CMakeFiles/pio_Telemetrix4RpiPico.dir/Telemetrix4RpiPico.c.obj
In file included from /home/dominecf/tm/Telemetrix4RpiPico/Telemetrix4RpiPico.c:34:
/home/dominecf/tm/Telemetrix4RpiPico/include/Telemetrix4RpiPico.h:13:10: fatal error: pico/stdlib.h: No such file or directory
   13 | #include "pico/stdlib.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pio_Telemetrix4RpiPico.dir/build.make:76: CMakeFiles/pio_Telemetrix4RpiPico.dir/Telemetrix4RpiPico.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1477: CMakeFiles/pio_Telemetrix4RpiPico.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by MrYsLab** [comment]
I am not sure if you are using VSCode to build the code, but I will set up a new environment using VSCode and see if it builds.
You may already know this, but if you have published open-source code, JetBrains provides free licenses to their products, including CLion. 
I will let you know the results when I can build from VSCode.

**Comment by FilipDominec** [comment]
Generally I am using gcc all the time, but I have been failing to compile Tmx with the official approach. Perhaps I just miss some step or option. 

Since I am not a programmer, but a physicist, and also getting a bit under pressure to return to my laboratory work ASAP, I can switch to VSCode or CLion for a while. 

Still I am convinced that it is good to cooperate on a single project, so I will be very thankful for any hint how to get it compile.

**Comment by FilipDominec** [comment]
Clearly there is some trouble with ```cmake``` or ```make``` not preparing all search paths for the compiler. 

I can play a cat-and-mouse game with the dependencies, manually supplying all paths like this
```
gcc -H -v -fsyntax-only Telemetrix4RpiPico.c -I/home/dominecf/bin/pico-sdk/src/common/pico_stdlib/include/ -I/home/dominecf/bin/pico-sdk/src/common/pico_base/include/ -I/home/dominecf/p/Telemetrix4RpiPico/generated/pico_base/ -I/home/dominecf/bin/pico-sdk/src/host/pico_platform/include/
...
```
which makes the compiler always complain about some **other** file missing. So perhaps I could get it compile eventually, but this is crazy. There has to be some easy trick that makes the compilation environment clean.

----

An important experiment for me - and easy one for you - would be if you made a super-simple project like ```blink.c``` using CLion. I would try to compile it and perhaps trace down what is its difference from the ```blink.c``` in the official PDF (which compiles smoothly on my computer).

**Comment by MrYsLab** [comment]
Ok. I will experiment without an IDE and let you know the result.

**Comment by MrYsLab** [comment]
I have attached a .zip file that contains the sample from the "Creating Your Own Project. "section 8 of the "Getting Started With Raspberry Pi Pico" document.

The directory called "test" contains the files that follow the tutorial. The testClion directory contains the CLion project that was built from test. 

Both compile in for their intended environment. 

I could not manually build Telemetrix4RpiPico contained in this repository, but I could rebuild using CLion loaded onto a new VirtualBox Ubuntu environment. There are a few non-obvious steps in doing so, but I was successful in doing so.

[test_play.zip](https://github.com/MrYsLab/Telemetrix4RpiPico/files/7173357/test_play.zip)

**Comment by FilipDominec** [comment]
Great, this will certainly enable me to learn what to fix. Thank you!

EDIT: After stripping down all generated (i.e. non-essential) files, only cmake_install.cmake, CMakeLists.txt, pico_sdk_import.cmake, and test.c remain. They are identical among the two compile environments. So I will continue searching for the origin of the error.

**Comment by FilipDominec** [comment]
Interestingly enough, there is Telemetrix4RpiPico.uf2 generated even if the compiler issues the "Fatal Error" shown above.

I didn't notice this before, thinking this is just a pre-compiled binary file downloaded along with the project. 

So I could have already proceeded to programming two days ago. If your compiling environment terminates without an error, consider this bug report to be invalid. 

However, in the future it would be useful to add step-by-step compilation using the procedure https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf which does not spit out error messages like this.

**Comment by MrYsLab** [comment]
I will close this issue. I cannot successfully  compile the 
Telemetrix4RpiPico files using the instructions in "getting started" without reported compile issues. I have no idea how to fix the compile issues outside of CLion. But since CLion works for both 
Telemetrix4RpiPico and the pico-examples files, I will not pursue this any further.

**Comment by FilipDominec** [comment]
Finally I can confirm the compilation errors were caused by my calling bare 
```
make
```
instead of 
```
make Telemetrix4RpiPico
```
That's all. With this command, everything finishes fine. 

Note: If header file(s) were changed, it may be also necessary to run this prior to compilation:
```
make clean
```

**Comment by MrYsLab** [comment]
I am glad you were able to get things to work. Thanks for letting me know.

**Comment by FilipDominec** [comment]
Finally I have spared some time to get things moving with Telemetrix; few PRs will need to be kindly reviewed and some conceptual questions could also be resolved. Actually, I can start off with one.
